/**
 * Update the Homebrew formula for hapi.
 *
 * This script:
 * 1. Reads checksums from release-artifacts/checksums.txt
 * 2. Generates an updated hapi.rb formula
 * 3. Optionally clones the tap repo, commits, and pushes
 *
 * Usage:
 *   # Generate formula locally (for review)
 *   bun run scripts/update-homebrew-formula.ts --version 0.1.0
 *
 *   # Generate and push to tap repository
 *   bun run scripts/update-homebrew-formula.ts --version 0.1.0 --push
 *
 * Environment:
 *   HOMEBREW_TAP_REPO - Git URL of the tap repository (default: https://github.com/jacobs-256/homebrew-hapi-nexus.git)
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

interface PlatformSha {
    darwinArm64: string;
    darwinAmd64: string;
}

function parseChecksums(checksumsPath: string): PlatformSha {
    const content = readFileSync(checksumsPath, 'utf-8');
    const lines = content.trim().split('\n');

    const shas: Partial<PlatformSha> = {};

    for (const line of lines) {
        const [sha, filename] = line.split('  ');
        if (!sha || !filename) continue;

        const match = filename.match(/^hapi-nexus-.+-hapi-(darwin-arm64|darwin-amd64)\.tar\.gz$/);
        if (!match) continue;

        if (match[1] === 'darwin-arm64') shas.darwinArm64 = sha;
        else if (match[1] === 'darwin-amd64') shas.darwinAmd64 = sha;
    }

    const missing: string[] = [];
    if (!shas.darwinArm64) missing.push('darwin-arm64');
    if (!shas.darwinAmd64) missing.push('darwin-amd64');

    if (missing.length > 0) {
        throw new Error(`Missing SHA256 checksums for: ${missing.join(', ')}`);
    }

    return shas as PlatformSha;
}

function generateFormula(version: string, shas: PlatformSha): string {
    return `# typed: false
# frozen_string_literal: true

class Hapi < Formula
  desc "Private multi-user AI coding agent control CLI"
  homepage "https://github.com/jacobs-256/hapi-nexus"
  version "${version}"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobs-256/hapi-nexus/releases/download/v#{version}/hapi-nexus-v#{version}-hapi-darwin-arm64.tar.gz"
      sha256 "${shas.darwinArm64}"
    else
      url "https://github.com/jacobs-256/hapi-nexus/releases/download/v#{version}/hapi-nexus-v#{version}-hapi-darwin-amd64.tar.gz"
      sha256 "${shas.darwinAmd64}"
    end
  end

  on_linux do
    odie "Install HAPI Nexus on Linux from GitHub Releases: https://github.com/jacobs-256/hapi-nexus/releases"
  end

  def install
    bin.install Dir["*/hapi"].first => "hapi"
  end

  def caveats
    <<~EOS
      Connect this client to your HAPI Nexus Hub:
        hapi auth login

      Start a runner for one or more allowed workspace roots:
        hapi runner start --workspace-root /path/to/projects
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hapi --version")
  end
end
`;
}

function printUsage(): void {
    console.log(`Usage:
  bun run scripts/update-homebrew-formula.ts --version <version> [--push]

Options:
  --version <version>  Version to update to (required)
  --push               Clone tap repo, commit and push changes
  --help               Show this help message

Examples:
  # Generate formula locally
  bun run scripts/update-homebrew-formula.ts --version 0.1.0

  # Push to tap repository
  bun run scripts/update-homebrew-formula.ts --version 0.1.0 --push
`);
}

async function main(): Promise<void> {
    const args = process.argv.slice(2);

    if (args.includes('--help') || args.includes('-h')) {
        printUsage();
        process.exit(0);
    }

    const versionIdx = args.indexOf('--version');
    if (versionIdx === -1 || !args[versionIdx + 1]) {
        console.error('Error: --version is required\n');
        printUsage();
        process.exit(1);
    }

    const version = args[versionIdx + 1];
    const shouldPush = args.includes('--push');
    const tapRepo = process.env.HOMEBREW_TAP_REPO || 'https://github.com/jacobs-256/homebrew-hapi-nexus.git';
    const checksumsPath = join(projectRoot, 'release-artifacts', 'checksums.txt');

    if (!existsSync(checksumsPath)) {
        console.error(`Error: Checksums file not found: ${checksumsPath}`);
        console.error('This file is generated by the CI workflow during release.');
        process.exit(1);
    }

    console.log(`Generating Homebrew formula for v${version}...\n`);

    // Parse checksums
    const shas = parseChecksums(checksumsPath);
    console.log('SHA256 checksums:');
    console.log(`  darwin-arm64: ${shas.darwinArm64}`);
    console.log(`  darwin-amd64: ${shas.darwinAmd64}\n`);

    // Generate formula content
    const formulaContent = generateFormula(version, shas);

    if (!shouldPush) {
        // Just output the formula locally
        const localFormulaDir = join(projectRoot, 'release-artifacts', 'Formula');
        mkdirSync(localFormulaDir, { recursive: true });

        const localFormulaPath = join(localFormulaDir, 'hapi.rb');
        writeFileSync(localFormulaPath, formulaContent);

        console.log(`Formula generated: ${localFormulaPath}\n`);
        console.log('To push to the tap repository, run with --push flag.');
        console.log(`Or manually copy to your homebrew-hapi-nexus repo's Formula/ directory.`);
        return;
    }

    // Clone and push to tap repository
    const githubToken = process.env.GITHUB_TOKEN;
    let cloneUrl = tapRepo;

    // Use token-authenticated URL in CI
    if (githubToken && tapRepo.includes('github.com')) {
        cloneUrl = tapRepo.replace('https://github.com/', `https://x-access-token:${githubToken}@github.com/`);
    }

    console.log(`Cloning ${tapRepo}...`);

    const tempDir = join(tmpdir(), `homebrew-tap-${Date.now()}`);
    mkdirSync(tempDir, { recursive: true });

    try {
        execSync(`git clone --depth 1 "${cloneUrl}" "${tempDir}"`, { stdio: 'pipe' });

        // Ensure Formula directory exists
        const formulaDir = join(tempDir, 'Formula');
        mkdirSync(formulaDir, { recursive: true });

        // Write formula
        const formulaPath = join(formulaDir, 'hapi.rb');
        writeFileSync(formulaPath, formulaContent);
        console.log(`Updated: ${formulaPath}`);

        // Configure git user for CI
        if (githubToken) {
            execSync('git config user.name "github-actions[bot]"', { cwd: tempDir, stdio: 'pipe' });
            execSync('git config user.email "github-actions[bot]@users.noreply.github.com"', { cwd: tempDir, stdio: 'pipe' });
        }

        // Commit and push
        execSync('git add Formula/hapi.rb', { cwd: tempDir, stdio: 'pipe' });

        try {
            execSync(`git commit -m "Update hapi to v${version}"`, { cwd: tempDir, stdio: 'pipe' });
            execSync('git push origin main', { cwd: tempDir, stdio: 'pipe' });
            console.log(`\nSuccessfully pushed hapi v${version} to homebrew-hapi-nexus`);
        } catch {
            console.log('\nNo changes to commit (formula already up to date)');
        }

        console.log('\nUsers can now install via:');
        console.log('  brew install jacobs-256/hapi-nexus/hapi');
    } finally {
        // Cleanup
        rmSync(tempDir, { recursive: true, force: true });
    }
}

main().catch((error) => {
    console.error('Error:', error.message || error);
    process.exit(1);
});
